---
title: "Análisis de las condiciones del océano frente a Perú durante los años 1990"
author: "Claudia Durand"
output: html_document
---

## I.Introducción

La corriente del fenómeno “El Niño” es la presencia de estas aguas cálidas a lo largo de las costas peruanas, fenómeno recurrente que tiene una duración de varios meses siendo un  calentamiento marino-costero manifestando los cambios que ocurren en las capas superficiales y subsuperficiales del océano vinculado a interacciones complejas con la atmósfera que se producen en el Océano Pacífico ecuatorial, a miles de kilómetros de la costa peruana(SENAMHI, 2015).




Se realizó un análisis de las condiciones oceanográficas drurante el año 1990.


## II.Materiales y método

1.Zona de estudio y metodología 

Para el estudio del ambiente marino se realizó entre  Puerto Pizarro (03° 24´0 S) y Los Palos (18° 19,0´S) donde se obtuvieron 740 registros de temperatura superficial del mar, 47 estaciones con roseta-CTDO distribuidos en los perfiles de Puerto Pizarro, Paita, Punta Falsa, Chicama, Chimbote, Punta Bermejo, Callao, Pisco, San Juan, Atico e Ilo además, las muestras de salinidad fueron analizadas por el método de inducción con el Portasal Guildline modelo 8410A. 

2.Análisis de datos 

Los promedios de la temperatura sobre el mar(TSM), anomalía de la temperatura sobre mar (ATSM) y Salinidad sobre mar (SSM) se realizaron con el programa estadístico R versión 3.4.0.

## III.Resultados y discusión

```r
install.packages("devtools")
devtools::install_github("roliveros-ramos/kali")
```
```r
library(ncdf4)
library(fields)
library(kali)
nc = nc_open("datos/sst.nc4")
sst = ncvar_get(nc, "to")
lat = ncvar_get(nc, "latitude")
lon = ncvar_get(nc, "longitude") - 360
image.map(lon, lat, sst[,,1])
```
### 1.Promedio de la TSM durante el año 1990
```r
PROM_TSM_1990= apply(sst[,,373:384], MARGIN=c(1,2), FUN=mean, na.rm=TRUE)
image.map(lon,lat,PROM_TSM_1990,main="Promedio de la TSM del año 1990")
```
La temperatura sobre mar (TSM) osciló entre 21°C promedio por la sur y 24°C promedio por la zona norte.

### 2.Promedio de la ATSM durante el año 1990

```r
library(ncdf4)
library(fields)
library(kali)
nc = nc_open("datos/sst.nc4")
sst = ncvar_get(nc, "to")
lat = ncvar_get(nc, "latitude")
lon = ncvar_get(nc, "longitude") - 360
image.map(lon, lat, sst[,,1])
TSM_total=apply(sst[,,1:552], MARGIN=c(1,2), FUN=mean, na.rm=TRUE)
PROM_TSM_1990= apply(sst[,,373:384], MARGIN=c(1,2), FUN=mean, na.rm=TRUE)
ATSM_1990=TSM_total-PROM_TSM_1990
image.map(lon,lat,ATSM_1990,main="Promedio de la ATSM del año 1990")
```
Según la ONI(Oceanic Niño Index), las anomalías de la temperatura sobre  mar para el año 1990 no superaron a 0.5 considerándose la no presencia de un evento Niño(Null,2017).

### 3.Promedio de la Salinidad sobre mar (SSM) durante el año 1990

```r
library(ncdf4)
library(fields)
library(kali)
nc = nc_open("datos/sss.nc4")
sss= ncvar_get(nc,"so")
lat = ncvar_get(nc, "latitude")
lon = ncvar_get(nc, "longitude") - 360
image.map(lon, lat, sss[,,1])
```

```r
PROM_SSM_1990=apply(sss[,,373:384],MARGIN=c(1,2),FUN=mean, na.rm=TRUE)
image.map(lon,lat,PROM_SSM_1990,main="Promedio de la SSM del año 1990")
```
Para el año 1990, las masas de agua Aguas Subtropicales superficiales mayores a  >35,1 ups estuvieron cerca a la costa , 

##IV.Conclusiones

1.La TSM para el año 1990 fueron ligeramente frías
2.

##V.Referencias

Null, J. (julio de 2017). golden Gates weather services . Obtenido de http://ggweather.com/enso/oni.htm

SENAMHI, S. N. (2015). SENAMHI. Obtenido de http://www.senamhi.gob.pe/pdf/Dossier-El-Nino-2015.pdf


